"""Creator Score Service — calculation of creator performance scores and role classification."""

from __future__ import annotations

from typing import List
import statistics


def normalize_value(value: float, max_value: float) -> float:
    """Normalize a value to the range [0, 1] using min-max normalization.
    
    Formula: normalized = min(value / max_value, 1.0)
    
    Args:
        value: The value to normalize
        max_value: The maximum value in the dataset
        
    Returns:
        Normalized value in range [0, 1]
    """
    if max_value == 0:
        return 0.0
    
    normalized = value / max_value
    return min(normalized, 1.0)


def calculate_consistency(gmv_per_video_list: List[float]) -> float:
    """Calculate consistency score based on GMV per video standard deviation.
    
    Lower standard deviation indicates higher consistency.
    Formula: consistency = 1 / (1 + std_dev)
    
    Args:
        gmv_per_video_list: List of GMV values per video
        
    Returns:
        Consistency score (higher is more consistent)
    """
    if not gmv_per_video_list or len(gmv_per_video_list) == 0:
        return 0.0
    
    if len(gmv_per_video_list) == 1:
        # Single video has perfect consistency
        return 1.0
    
    try:
        std_dev = statistics.stdev(gmv_per_video_list)
        consistency = 1 / (1 + std_dev)
        return consistency
    except statistics.StatisticsError:
        # Handle edge case where all values are the same
        return 1.0


def calculate_creator_score(
    total_gmv: float,
    avg_engagement_rate: float,
    video_count: int,
    gmv_per_video_list: List[float],
    max_gmv: float,
    max_engagement: float,
    max_video_count: int,
    max_consistency: float
) -> float:
    """Calculate composite creator score based on multiple performance metrics.
    
    Formula:
    creator_score = (0.4 × normalized_gmv) + 
                    (0.3 × normalized_engagement) + 
                    (0.2 × normalized_consistency) + 
                    (0.1 × normalized_video_count)
    
    All components are normalized to [0, 1] range before applying weights.
    
    Args:
        total_gmv: Total GMV generated by creator
        avg_engagement_rate: Average engagement rate across all videos
        video_count: Number of videos created
        gmv_per_video_list: List of GMV values per video for consistency calculation
        max_gmv: Maximum GMV in the dataset (for normalization)
        max_engagement: Maximum engagement rate in the dataset (for normalization)
        max_video_count: Maximum video count in the dataset (for normalization)
        max_consistency: Maximum consistency score in the dataset (for normalization)
        
    Returns:
        Creator score in range [0, 1]
    """
    # Calculate normalized components
    normalized_gmv = normalize_value(total_gmv, max_gmv)
    normalized_engagement = normalize_value(avg_engagement_rate, max_engagement)
    normalized_video_count = normalize_value(video_count, max_video_count)
    
    # Calculate consistency and normalize it
    consistency = calculate_consistency(gmv_per_video_list)
    normalized_consistency = normalize_value(consistency, max_consistency)
    
    # Apply weighted formula
    creator_score = (
        0.4 * normalized_gmv +
        0.3 * normalized_engagement +
        0.2 * normalized_consistency +
        0.1 * normalized_video_count
    )
    
    # Ensure score is in [0, 1] range
    return min(max(creator_score, 0.0), 1.0)


def classify_creator_role(score: float) -> str:
    """Classify creator role based on creator score.
    
    Classification thresholds:
    - Superstar: score >= 0.8
    - Rising Star: 0.6 <= score < 0.8
    - Consistent Performer: 0.4 <= score < 0.6
    - Underperformer: score < 0.4
    
    Args:
        score: Creator score in range [0, 1]
        
    Returns:
        Creator role classification string
    """
    if score >= 0.8:
        return "Superstar"
    elif score >= 0.6:
        return "Rising Star"
    elif score >= 0.4:
        return "Consistent Performer"
    else:
        return "Underperformer"
