-- =============================================================================
-- Migration 007: Analytics Platform - Influencer Extensions
-- Extends influencers table with analytics-specific fields
-- =============================================================================

-- Add analytics columns to influencers table
-- These columns support creator intelligence and performance scoring
ALTER TABLE influencers
    ADD COLUMN IF NOT EXISTS creator_role VARCHAR(20) NOT NULL DEFAULT 'influencer',
    ADD COLUMN IF NOT EXISTS creator_score NUMERIC(10, 4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS estimated_revenue NUMERIC(18, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS avg_views BIGINT NOT NULL DEFAULT 0;

-- Create indexes for analytics queries
CREATE INDEX IF NOT EXISTS idx_influencers_creator_role ON influencers(creator_role);
CREATE INDEX IF NOT EXISTS idx_influencers_creator_score ON influencers(creator_score DESC);

-- Field descriptions:
-- creator_role: Classification of creator type (influencer | affiliator | hybrid)
-- creator_score: Composite performance score (0-1 range) calculated from GMV, engagement, consistency, and video count
-- estimated_revenue: Cached total GMV generated by creator for performance optimization
-- avg_views: Cached average views per video for performance optimization
